export const GET_LOCATION_DATA_SUCCESS = "GET_LOCATION_DATA_SUCCESS";
export const GET_LOCATION_DATA_FAIL = "GET_LOCATION_DATA_FAIL";
export const CREATE_LOCATION_DATA_SUCCESS = "CREATE_LOCATION_DATA_SUCCESS";
export const CREATE_LOCATION_DATA_FAIL = "CREATE_LOCATION_DATA_FAIL";
export const UPDATE_LOCATION_DATA_SUCCESS = "UPDATE_LOCATION_DATA_SUCCESS";
export const UPDATE_LOCATION_DATA_FAIL = "UPDATE_LOCATION_DATA_FAIL";
